services:
  - type: web
    name: garmin-health-sync
    runtime: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: GARMIN_OAUTH1
        sync: false
      - key: GARMIN_OAUTH2
        sync: false
